### ISSUE TITLE
Command: space conversation

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/ribose-cli#5]
# Conversation

## List

```sh
ribose space conversation list --space-id <uuid>
ribose space conversation list --space-id <uuid> --format json
ribose space conversation list --space-id <uuid> --format json --start 0 --length 25
```

## Add

```sh
ribose space conversation add --space-id <uuid> --title "conversation title"
```

## Remove

```sh
ribose space conversation add --space-id <uuid> --conversation-id <uuid>
```

# Message

## List

```sh
ribose space conversation-message list --space-id <uuid> --conversation-id <uuid>
ribose space conversation-message list --space-id <uuid> --conversation-id <uuid> --start 0 --length 25
```

## Add

```sh
ribose space conversation-message add --space-id <uuid> --conversation-id <uuid> --message-body "New Message Body"
```

## Edit

```sh
ribose space conversation-message edit --space-id <uuid> --message-id <uuid> --message-body "My New Content"
```

## Remove

```sh
ribose space conversation-message remove --space-id <uuid> --message-id <uuid>
```

**Comment by abunashir** [comment]
Hi @ronaldtse, I have added all of the above interfaces in the last couple of PR's there are some cleanup/refactoring will follow soon, but could you please have a look into #18 , #19, #20 , #21 , #22 , #23 and #24 and let me know thoughts?

**Comment by abunashir** [comment]
There were little bit changes in the structure of the commands, but all of the above commands are already implemented as bellows.

Conversation

<img width="734" alt="screenshot 2017-12-05 14 25 08" src="https://user-images.githubusercontent.com/1220911/33594875-4aff148e-d9c8-11e7-90b7-39eb5574e78d.png">


Message

<img width="1049" alt="screenshot 2017-12-05 14 27 20" src="https://user-images.githubusercontent.com/1220911/33594906-6d84911e-d9c8-11e7-8e3c-a2bf5f12b287.png">
